### ISSUE TITLE
Views - visibility and access based on user groups

### ISSUE THREAD

**Issue by cedricfrancoys** [equalframework/equal-ui#4]
Support for permissions on header actions (in addition to back-end logic)

```
[ACTION]:
    id:
    access:
    groups: []
```

Functioning similar to 'visible'. If the user doesn't have the rights, display message: 'You don't have rights to display this view'."
